In [62]:
import numpy as np
import math as mt
import sympy as sp
from sympy.physics.quantum import TensorProduct as TP
from math import sqrt
import sys
import random

In [63]:
#Qubits iniciais
qbit0= np.matrix([1,0]).transpose()
qbit1= np.matrix([0,1]).transpose()


#Porta H
H = 1/sqrt(2)*(np.matrix([[1,1], [1,-1]]))

#Aplicação da porta Hadamard no qubit qx
Hqbit0= H*qbit0
#print(Hqbit0)

#Aplicação da porta CNOT
CNOT = np.matrix([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])

#Base de Bell estado |00>

#Definição Alvo e Controle
AC= TP(Hqbit0,qbit0)
#print(AC)

Bell00 = CNOT * AC

#print(Bell00)

   

In [64]:
#Determinação do qubit para o protocolo
Message_alfa = float(input('Qual o estado alfa do Qubit que deseja enviar?'))
Message_beta = float(input('Qual o estado beta do Qubit que deseja enviar?'))


#Verifica se a soma é igual a 1 (condição de normalização)
if not mt.isclose(Message_alfa  + Message_beta, 1.0):
    print("Erro: A soma das entradas não é igual a 1.")
    sys.exit()
    
#Determina a mensagem a ser enviada
Message = (Message_alfa * qbit0) + (Message_beta * qbit1)

print(Message)

#Estado psi_0 

psi_0 = TP(qbit0, qbit0, qbit0) + TP(qbit0, qbit1, qbit1) + TP(qbit1,qbit0, qbit0) + TP(qbit1,qbit1,qbit1)

#Aplicação da porta CNOT
#Dimensionamento para 3 qubits
#Porta I
I = np.matrix ([[1,0], [0,1]])
CNOT_I = TP(CNOT,I)

#print(CNOT_I)
psi_1 = CNOT_I * psi_0

#print(psi_1)

#Aplicação da porta Hadamard
H_Message_alfa = H * (Message_alfa * qbit0)
H_Message_beta = H * (Message_beta * qbit1)

#print(H_Message_alfa, H_Message_beta)

Qual o estado alfa do Qubit que deseja enviar?0.5
Qual o estado beta do Qubit que deseja enviar?0.5
[[0.5]
 [0.5]]


In [65]:
#Medida e Reconstrução da Mensagem

estadoa0 = float(H_Message_alfa[0][0])
estadoa1 = float(H_Message_alfa[1][0])
estadob0 = float(H_Message_beta[0][0])
estadob1 = float(H_Message_beta[1][0])


#Determinação dos estados do qbitmensagem
a0 = np.matrix([estadoa0,0]).transpose()
a1 = np.matrix([0,estadoa1]).transpose()
b0 = np.matrix([estadob0,0]).transpose()
b1 = np.matrix([0,estadob1]).transpose()

print(a0,a1,b0,b1)

#Aplicação de ruído
#Determinando os ruídos
bitflip = np.matrix([[0, 1], [1, 0]])
phaseflip = np.matrix([[1, 0], [0, -1]])
noisebit = 0
# Escolha do ruído aplicado
while True:
    noise = input('Escolha o ruído:[0]- sem ruído, [1]- bitflip, [2]- phaseflip: ')
    if noise in ['0', '1', '2']:
        noise = int(noise)
        break
    else:
        print("Opção inválida. Por favor, digite 0, 1, 2 ou 3.")

if noise == 1:
    noisebit = bitflip
elif noise == 2:
    noisebit = phaseflip
elif noise == 0:
    noisebit = 1
    
print(noisebit)
#Determinação dos possíveis estados da Mensagem

#Medição

estado_00 = TP(qbit0, qbit0)
estado_11 = TP(qbit1, qbit1)
estado_10 = TP(qbit1, qbit0)
estado_01 = TP(qbit0, qbit1)

group_estados = [estado_00,estado_11,estado_10,estado_01]
chosen_estados = random.choice(group_estados)
Medição = chosen_estados

del estado_00, estado_11, estado_10, estado_01

print(Medição)

[[0.35355339]
 [0.        ]] [[0.        ]
 [0.35355339]] [[0.35355339]
 [0.        ]] [[ 0.        ]
 [-0.35355339]]
Escolha o ruído:[0]- sem ruído, [1]- bitflip, [2]- phaseflip, [3]- bitphaseflip: 3
[[ 1  1]
 [ 1 -1]]
[[0]
 [0]
 [0]
 [1]]


In [61]:
#Reconstrução da Mensagem
#Define o qubit mensagem em função do estado medido
if  np.all(Medição == (TP(qbit0,qbit0))):
    Message_tp = (a0-b1)
elif  np.all(Medição == (TP(qbit1,qbit1))):
    Message_tp = (a1-b0)
elif  np.all(Medição == (TP(qbit0,qbit1))):
    Message_tp = (a1+b0)
elif np.all(Medição == (TP(qbit1,qbit0))):
    Message_tp = (a0+b1)
#print(Message_tp) 


#Recupera a mensagem Original

# Define as matrizes de Pauli
X = np.matrix([[0, 1], [1, 0]])
Z = np.matrix([[1, 0], [0, -1]])

if np.all(Message_tp == (a0-b1)):
    Message_final = Message_tp
elif np.all(Message_tp == (a1-b0)):
    Message_final = Z * X * Message_tp 
elif np.all(Message_tp == (a1+b0)):
    Message_final = X * Message_tp 
elif np.all(Message_tp == (a0+b1)):
    Message_final = Z * Message_tp 
    
Mensagem_teletransportada = Message_final*sqrt(2)    

print(Mensagem_teletransportada)


#Aplicação de ruído
#Determinando os ruídos
bitflip = np.matrix([[0, 1], [1, 0]])
phaseflip = np.matrix([[1, 0], [0, -1]])
noisebit = 0

# Escolha do ruído aplicado
while True:
    noise = input('Escolha o ruído:[0]- sem ruído, [1]- bitflip, [2]- phaseflip: ')
    if noise in ['0', '1', '2']:
        noise = int(noise)
        break
    else:
        print("Opção inválida. Por favor, digite 0, 1, 2 ou 3.")

if noise == 1:
    noisebit = bitflip
elif noise == 2:
    noisebit = phaseflip
elif noise == 0:
    noisebit = 1
    
print(noisebit)

aplicação_noise = noisebit * Mensagem_teletransportada
print(aplicação_noise)

if np.all(Mensagem_teletransportada == Message):
    print('Teletransporte concluído com sucesso')
else:
    print('Falha no Teletransporte')

if np.all(aplicação_noise != Message):
    print('Mensagem com ruídos')
else:
    print('Mensagem sem ruídos')






[[0.5]
 [0.5]]
[[0.5]
 [0.5]]
Teletransporte concluído com sucesso
Mensagem sem ruídos
