In [1]:
import numpy as np
import math as mt
import sympy as sp
from sympy.physics.quantum import TensorProduct as TP
from math import sqrt
import sys
import random

In [2]:
#Qubits iniciais
qbit0= np.matrix([1,0]).transpose()
qbit1= np.matrix([0,1]).transpose()


#Porta H
H = np.matrix([[1,1], [1,-1]])

#Porta I
I = np.matrix ([[1,0], [0,1]])

#Dimensionamento
H_I = TP(H,I)*(1/sqrt(2))


#Aplicação da porta Hadamard
qbit00 = TP(qbit0,qbit0)
qbit01 = TP(qbit0,qbit1)
qbit10 = TP(qbit1,qbit0)
qbit11 = TP(qbit1,qbit1)


#Estados de Bell
Bell00= H_I * qbit00
Bell01 = H_I * qbit01
Bell10 = H_I * qbit10
Bell11 = H_I * qbit11


#print(Bell00,Bell01,Bell10,Bell11)
   

In [10]:
#Determinação do qubit para o protocolo
Message_alfa = float(input('Qual o estado alfa do Qubit que deseja enviar?'))
Message_beta = float(input('Qual o estado beta do Qubit que deseja enviar?'))


#Verifica se a soma é igual a 1 (condição de normalização)
if not mt.isclose(Message_alfa  +Message_beta, 1.0):
    print("Erro: A soma das entradas não é igual a 1.")
    sys.exit()
    
#Determina a mensagem a ser enviada
Message = (Message_alfa * qbit0) + (Message_beta * qbit1)

print(Message)
#Estado psi_0 (Message + Bell)

psi_0 = TP(qbit0, qbit00) + TP(qbit0, qbit11) + TP(qbit1,qbit00) + TP(qbit1,qbit11)
#print(psi_0)

#Aplicação da porta CNOT
CNOT = np.matrix([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])
CNOT_I = TP(CNOT,I)

#print(CNOT_I)
psi_1 = CNOT_I * psi_0

#print(psi_1)

#Aplicação da porta Hadamard
H_Message_alfa = H * (Message_alfa * qbit0)
H_Message_beta = H * (Message_beta * qbit1)

print(H_Message_alfa, H_Message_beta)

Qual o estado alfa do Qubit que deseja enviar?0.5
Qual o estado beta do Qubit que deseja enviar?0.5
[[0.5]
 [0.5]]
[[0.5]
 [0.5]] [[ 0.5]
 [-0.5]]


In [8]:
0.2+0.3==0.5
0.1+0.3==0.4

True

In [4]:
#Medida e Reconstrução da Mensagem

estadoa0 = float(H_Message_alfa[0][0])
estadoa1 = float(H_Message_alfa[1][0])
estadob0 = float(H_Message_beta[0][0])
estadob1 = float(H_Message_beta[1][0])


#Determinação dos estados do qbitmensagem
a0 = np.matrix([estadoa0,0]).transpose()
a1 = np.matrix([0,estadoa1]).transpose()
b0 = np.matrix([estadob0,0]).transpose()
b1 = np.matrix([0,estadob1]).transpose()

print(a0,a1,b0,b1)

#Determinação dos possíveis estados da Mensagem

#Medição

estado_00 = qbit00
estado_11 = qbit11
estado_10 = qbit10
estado_01 = qbit01

group_estados = [estado_00,estado_11,estado_10,estado_01]
chosen_estados = random.choice(group_estados)
Medição = chosen_estados

del estado_00, estado_11, estado_10, estado_01

print(Medição)

[[0.5]
 [0. ]] [[0. ]
 [0.5]] [[0.5]
 [0. ]] [[ 0. ]
 [-0.5]]
[[0]
 [1]
 [0]
 [0]]


In [5]:
#Reconstrução da Mensagem

# Define as matrizes de Pauli
X = np.matrix([[0, 1], [1, 0]])
Z = np.matrix([[1, 0], [0, -1]])

# Define o qubit mensagem em função do estado medido
if  np.all(Medição == qbit00):
    Message_tp = a0-b1
elif  np.all(Medição == qbit11):
    Message_tp = a1-b0
elif  np.all(Medição == qbit01):
    Message_tp = a1+b0
else:
    Message_tp = a0+b1
#print(Message_tp) 

#Recupera a mensagem Original

if np.all(Message_tp == a0-b1):
    Message_final = Message_tp
elif np.all(Message_tp == a1-b0):
    Message_final = Z * X * Message_tp  
elif np.all(Message_tp == a1+b0):
    Message_final = X * Message_tp 
elif np.all(Message_tp == a0+b1):
    Message_final = Z * Message_tp 
    
if np.all(Message_final == Message):
    print('Teletransporte concluído com sucesso')
else:
    print('Falha no Teletransporte')

print(Message_final)    
    

Teletransporte concluído com sucesso
[[0.5]
 [0.5]]
