In [1]:
import numpy as np
import math as mt
import sympy as sp
from sympy.physics.quantum import TensorProduct as TP
from math import sqrt
import sys
import random

In [2]:
#Qubits iniciais
qbit0= np.matrix([1,0]).transpose()
qbit1= np.matrix([0,1]).transpose()


#Porta H
H = 1/sqrt(2)*(np.matrix([[1,1], [1,-1]]))

#Aplicação da porta Hadamard no qubit qx
Hqbit0= H*qbit0
#print(Hqbit0)

#Aplicação da porta CNOT
CNOT = np.matrix([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])

#Base de Bell estado |00>

#Definição Alvo e Controle
AC= TP(Hqbit0,qbit0)
#print(AC)

Bell00 = CNOT * AC

#print(Bell00)

   

In [3]:
CNOT

matrix([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0]])

In [4]:
AC

matrix([[0.70710678],
        [0.        ],
        [0.70710678],
        [0.        ]])

In [8]:
dir(np.array)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [3]:
#Determinação do qubit para o protocolo
Message_alfa = float(input('Qual o estado alfa do Qubit que deseja enviar?'))
Message_beta = float(input('Qual o estado beta do Qubit que deseja enviar?'))


#Verifica se a soma é igual a 1 (condição de normalização)
if not mt.isclose(Message_alfa  +Message_beta, 1.0):
    print("Erro: A soma das entradas não é igual a 1.")
    sys.exit()
    
#Determina a mensagem a ser enviada
Message = (Message_alfa * qbit0) + (Message_beta * qbit1)

print(Message)

#Estado psi_0 

psi_0 = TP(qbit0, qbit0, qbit0) + TP(qbit0, qbit1, qbit1) + TP(qbit1,qbit0, qbit0) + TP(qbit1,qbit1,qbit1)

#Aplicação da porta CNOT
#Dimensionamento para 3 qubits
#Porta I
I = np.matrix ([[1,0], [0,1]])
CNOT_I = TP(CNOT,I)

#print(CNOT_I)
psi_1 = CNOT_I * psi_0

#print(psi_1)

#Aplicação da porta Hadamard
H_Message_alfa = H * (Message_alfa * qbit0)
H_Message_beta = H * (Message_beta * qbit1)

#print(H_Message_alfa, H_Message_beta)

Qual o estado alfa do Qubit que deseja enviar?0.75
Qual o estado beta do Qubit que deseja enviar?0.25
[[0.75]
 [0.25]]


In [4]:
#Medida e Reconstrução da Mensagem

estadoa0 = float(H_Message_alfa[0][0])
estadoa1 = float(H_Message_alfa[1][0])
estadob0 = float(H_Message_beta[0][0])
estadob1 = float(H_Message_beta[1][0])


#Determinação dos estados do qbitmensagem
a0 = np.matrix([estadoa0,0]).transpose()
a1 = np.matrix([0,estadoa1]).transpose()
b0 = np.matrix([estadob0,0]).transpose()
b1 = np.matrix([0,estadob1]).transpose()

print(a0,a1,b0,b1)

#Determinação dos possíveis estados da Mensagem

#Medição

estado_00 = TP(qbit0, qbit0)
estado_11 = TP(qbit1, qbit1)
estado_10 = TP(qbit1, qbit0)
estado_01 = TP(qbit0, qbit1)

group_estados = [estado_00,estado_11,estado_10,estado_01]
chosen_estados = random.choice(group_estados)
Medição = chosen_estados

del estado_00, estado_11, estado_10, estado_01

print(Medição)

[[0.53033009]
 [0.        ]] [[0.        ]
 [0.53033009]] [[0.1767767]
 [0.       ]] [[ 0.       ]
 [-0.1767767]]
[[0]
 [1]
 [0]
 [0]]


In [5]:
#Reconstrução da Mensagem
#Define o qubit mensagem em função do estado medido
if  np.all(Medição == (TP(qbit0,qbit0))):
    Message_tp = (a0-b1)
elif  np.all(Medição == (TP(qbit1,qbit1))):
    Message_tp = (a1-b0)
elif  np.all(Medição == (TP(qbit0,qbit1))):
    Message_tp = (a1+b0)
elif np.all(Medição == (TP(qbit1,qbit0))):
    Message_tp = (a0+b1)
#print(Message_tp) 

#Recupera a mensagem Original

# Define as matrizes de Pauli
X = np.matrix([[0, 1], [1, 0]])
Z = np.matrix([[1, 0], [0, -1]])

if np.all(Message_tp == (a0-b1)):
    Message_final = Message_tp
elif np.all(Message_tp == (a1-b0)):
    Message_final = Z * X * Message_tp 
elif np.all(Message_tp == (a1+b0)):
    Message_final = X * Message_tp 
elif np.all(Message_tp == (a0+b1)):
    Message_final = Z * Message_tp 

Mensagem_teletransportada = Message_final*sqrt(2)   
    
if np.all(Mensagem_teletransportada == Message):
    print('Teletransporte concluído com sucesso')
else:
    print('Falha no Teletransporte')

print(Message, Mensagem_teletransportada)



#Soma_prob_final=0
#Soma_prob_inicial=0

#for linha in Mensagem_teletransportada:
#    for elemento in linha:
#        Soma_prob_final += elemento

#for linha in Message:
#    for elemento in linha:
#        Soma_prob_inicial += elemento  
        
#if Soma_prob_final == Soma_prob_inicial:
#    print('Teletransporte concluído com sucesso')
#else:
#    print('Erro no Teletransporte')
    
#print(Soma_prob_final, Soma_prob_inicial)


Teletransporte concluído com sucesso
[[0.75]
 [0.25]] [[0.75]
 [0.25]]
