In [3]:
import numpy as np
import math as mt
import sympy as sp
from sympy.physics.quantum import TensorProduct as TP
from math import sqrt

#Qubits iniciais
qbit = int(input('Qual o estado do Qubit que deseja emaranhar?'))
qbit0= np.matrix([1,0]).transpose()
qbit1= np.matrix([0,1]).transpose()

if qbit == 0:
    qbit = qbit0
elif qbit == 1:
    qbit = qbit1
else:
    print('Estado não permitido, tente novamente')
print (qbit)

Qual o estado do Qubit que deseja emaranhar?1
[[0]
 [1]]


In [2]:
#Porta H
H = np.matrix([[1,1], [1,-1]])

#Porta I
I = np.matrix ([[1,0], [0,1]])

#Dimensionamento
HI = TP(H,I)*(1/sqrt(2))

print(HI)

#Aplicação da porta Hadamard
qbitxy= TP(qbit,qbit)

print(qbitxy)

Hqbit= HI * qbitxy

print(Hqbit)

[[ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.70710678  0.          0.70710678]
 [ 0.70710678  0.         -0.70710678  0.        ]
 [ 0.          0.70710678  0.         -0.70710678]]
[[1]
 [0]
 [0]
 [0]]
[[0.70710678]
 [0.        ]
 [0.70710678]
 [0.        ]]


In [23]:
# Porta CNOT
CNOT = np.matrix([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])

# Aplicação da porta CNOT
Bell = CNOT * Hqbit

print(Bell)

[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]


In [26]:
# Estado psi1
# Aplicação de CNOT qubit alvo

psi1 = CNOT * Bell

print(psi1)

[[0.70710678]
 [0.        ]
 [0.70710678]
 [0.        ]]
