In [33]:
import numpy as np
import math as mt
import sympy as sp
from sympy.physics.quantum import TensorProduct as TP
from math import sqrt

#Qubits iniciais
qbit = int(input('Qual o estado do Qubit que deseja emaranhar?'))
qbit0= np.matrix([1,0]).transpose()
qbit1= np.matrix([0,1]).transpose()

if qbit == 0:
    qbit = qbit0
elif qbit == 1:
    qbit = qbit1
else:
    print('Estado não permitido, tente novamente')
print (qbit)

Qual o estado do Qubit que deseja emaranhar?0
[[1]
 [0]]


In [34]:
#Porta H
H = np.matrix([[1,1], [1,-1]])

#Porta I
I = np.matrix ([[1,0], [0,1]])

#Dimensionamento
HI = TP(H,I)*(1/sqrt(2))

print(HI)

#Aplicação da porta Hadamard
qbitxy= TP(qbit,qbit)

print(qbitxy)

Hqbit= HI * qbitxy

print(Hqbit)

[[ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.70710678  0.          0.70710678]
 [ 0.70710678  0.         -0.70710678  0.        ]
 [ 0.          0.70710678  0.         -0.70710678]]
[[1]
 [0]
 [0]
 [0]]
[[0.70710678]
 [0.        ]
 [0.70710678]
 [0.        ]]


In [35]:
# Porta CNOT
CNOT = np.matrix([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])

# Aplicação da porta CNOT
Bell = CNOT * Hqbit

print(Bell)

[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]


In [42]:
# Definindo o qubit Mensagem

a = np.matrix([[1,0]]).transpose()
b = np.matrix([[0,1]]).transpose()

In [31]:
# Aplicando a condição lógica da porta CNOT

# Definindo as tríades de qubits
a1 = np.matrix([0,0,0])
a2 = np.matrix([0,1,1])
b1 = np.matrix([1,0,0])
b2 = np.matrix([1,1,1])

# Aplicando a condição da porta CNOT em função do valor do primeiro qubit e modificando o segundo.

if a1[0, 0] == 0:
    # Não muda o valor da segunda posição
    pass
else:
    # Muda o valor da segunda posição
    if a1[0, 1] == 0:
        a1[0, 1] = 1
    else:
        a1[0, 1] = 0
        
if a2[0, 0] == 0:
    pass
else:
    if a2[0, 1] == 0:
        a2[0, 1] = 1
    else:
        a2[0, 1] = 0
        
if b1[0, 0] == 0:
    pass
else:
    if b1[0, 1] == 0:
        b1[0, 1] = 1
    else:
        b1[0, 1] = 0
        
if b2[0, 0] == 0:
    pass
else:
    if b2[0, 1] == 0:
        b2[0, 1] = 1
    else:
        b2[0, 1] = 0
        
print(a1, a2, b1, b2)  

# Definindo o produto tensorial entre o segundo e terceiro qubit
#a1
q2a1 = a1[0,1]
# Define o valor do vetor que representa o estado
if q2a1 == 0:
    tp1a1 = np.matrix([1,0]).transpose()
else:
    tp1a1 = np.matrix([0,1]).transpose()
    
q3a1 = a1[0,2]
if q3a1 == 0:
    tp2a1 = np.matrix([1,0]).transpose()
else:
    tp2a1 = np.matrix([0,1]).transpose()
    
tpa1 = TP(tp1a1, tp2a1)

#a2
q2a2 = a2[0,1]
if q2a2 == 0:
    tp1a2 = np.matrix([1,0]).transpose()
else:
    tp1a2 = np.matrix([0,1]).transpose()
    
q3a2 = a2[0,2]
if q3a2 == 0:
    tp2a2 = np.matrix([1,0]).transpose()
else:
    tp2a2 = np.matrix([0,1]).transpose()
    
tpa2 = TP(tp1a2, tp2a2)

#b1
q2b1 = b1[0,1]
if q2b1 == 0:
    tp1b1 = np.matrix([1,0]).transpose()
else:
    tp1b1 = np.matrix([0,1]).transpose()
    
q3b1 = b1[0,2]
if q3b1 == 0:
    tp2b1 = np.matrix([1,0]).transpose()
else:
    tp2b1 = np.matrix([0,1]).transpose()
    
tpb1 = TP(tp1b1, tp2b1)

q2b1 = b1[0,1]
# Define o valor do vetor que representa o estado
if q2b1 == 0:
    tp1b1 = np.matrix([1,0]).transpose()
else:
    tp1b1 = np.matrix([0,1]).transpose()
    
q3b1 = b1[0,2]
if q3b1 == 0:
    tp2b1 = np.matrix([1,0]).transpose()
else:
    tp2b1 = np.matrix([0,1]).transpose()
    
tpb1 = TP(tp1b1, tp2b1)

print(tp1b1,tp2b1)

#b2
q2b2 = b2[0,1]
if q2b2 == 0:
    tp1b2 = np.matrix([1,0]).transpose()
else:
    tp1b2 = np.matrix([0,1]).transpose()
    
q3b2 = b2[0,2]
if q3b2 == 0:
    tp2b2 = np.matrix([1,0]).transpose()
else:
    tp2b2 = np.matrix([0,1]).transpose()
    
tpb2 = TP(tp1b2, tp2b2)



print(tpa1, tpa2, tpb1, tpb2)


[[0 0 0]] [[0 1 1]] [[1 1 0]] [[1 0 1]]
[[0]
 [1]] [[1]
 [0]]
[[1]
 [0]
 [0]
 [0]] [[0]
 [0]
 [0]
 [1]] [[0]
 [0]
 [1]
 [0]] [[0]
 [1]
 [0]
 [0]]


In [43]:
# Aplicando a porta Hadamard em psi Mensagem

Ha = H*a
Hb = H*b

print(Ha, Hb)

[[1]
 [1]] [[ 1]
 [-1]]


Matrix([[1, 1], [1, -1]])


= + a*b*c + a + b - c


ShapeError: Matrix size mismatch: (4, 1) + (8, 1)

ShapeError: Matrix size mismatch: (4, 1) + (8, 1)

ShapeError: Matrix size mismatch: (4, 1) + (8, 1)

ShapeError: Matrix size mismatch: (4, 1) + (8, 1)

ShapeError: Matrix size mismatch: (4, 1) + (8, 1)